### ISSUE TITLE
Makefile enchantment - partial compilation

### ISSUE THREAD

**Issue by zaprzanstwo** [DeriDreri/osh-ObnoxiousSHell#4]
## Goal
Instead of compiling all source files into an executable in one go, compile only the source files which were changed into object files, then link them together. 

## Sources 
Duckduckgo it

## Requirements
- [ ] Create rules compiling object files, kept in a new directory
- [ ] Change target rule to link all the object files
- [ ] Make sure to add rule in `.gitignore` to not add object files to the repisotry

**Comment by DeriDreri** [comment]
Implemented in d8bbe699fdcd991bfdadb836a67be821fcefd6cb

**Comment by zaprzanstwo** [comment]
Implemented in d8bbe699fdcd991bfdadb836a67be821fcefd6cb
